linters:
  Comment:
    enabled: false
  QualifyingElement:
    enabled: false
  ImportantRule:
    enabled: false
  PropertySortOrder:
    order: recess
  DeclarationOrder:
    enabled: false
  PrivateNamingConvention:
    enabled: true
